version: '3'

services:
  webserver:
    build: ./apps/nginx
    env_file: .env
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./public/conf.d:/etc/nginx/conf.d
      - ./public/ssl:/etc/nginx/certs
      - ./public/snippets:/etc/nginx/snippets
      - static-content:/usr/share/nginx/html
    links:
      - 'api:publisher-api'
  api:
    image: publisher/api
    build: ./apps/server
    environment:
      NODE_ENV: production
      PORT: 3000
      SERVER_PUBLIC_PATH: /usr/html
    env_file: .env
    volumes:
      - static-content:/usr/html
    expose:
      - '3000'

volumes:
  static-content:
